package com.coderman.bizedu.model.log;

import com.coderman.api.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: auth_log
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="LogModel", description = "auth_log 实体类")
public class LogModel extends BaseModel {
    

    @ApiModelProperty(value = "日志id")
    private Integer logId;

    @ApiModelProperty(value = "日志内容")
    private String logInfo;

    @ApiModelProperty(value = "模块类型")
    private Integer logModule;

    @ApiModelProperty(value = "日志等级")
    private Integer logLevel;

    @ApiModelProperty(value = "操作人id")
    private Integer userId;

    @ApiModelProperty(value = "操作人账号")
    private String username;

    @ApiModelProperty(value = "操作人姓名")
    private String realName;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;
}