server:
  port: 8989
spring:
  application:
    name: admin
  datasource:
    username: root
    password: DES@402239CE2BC2750281C31F4CEA2619B91D0AE9C2129F6555
    url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/admin_pro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 10.41.188.160
    password: DES@99D5518076FE8F32214D66F4B59766B7
    port: 6379

#服务端配置
sync:
  # es 配置
  elasticsearch:
    clusterName: sync
    hosts: 10.41.188.160:9200
    # hosts: 165.154.133.250:9200
    scheme: http
    connectTimeOut: 5000
    socketTimeOut: 60000
    connectionRequestTimeOut: 500
    maxConnectNum: 100
    maxConnectNumPerRoute: 100
  activemq:
    queueName: SYNC_QUEUE_DEV
    brokerUrl: vm://localhost
    username: admin
    password: 123456
  # 同步回调配置
  callback:
    destList:
      - project: admin
        url: https://api.coderman.love
  # 同步系统jdbc配置
  jdbc:
    commonMaxIdle: 20
    commonMaxWait: 1000
    commonMinIdle: 10
    commonMaxActive: 800
    commonTimeout: 20
    mysqlUsername: root
    mysqlPassword: 123456
    mysqlInitialSize: 10
    mysqlMinEvictableIdleTimeMillis: 40000
    mysqlTimeBetweenEvictionRunsMillis: 10000
    mysqlTestOnBorrow: false
    mysqlTestOnReturn: false
    mysqlTestWhileIdle: true
    dbList:

      - dbname: admin_pro
        password: DES@402239CE2BC2750281C31F4CEA2619B91D0AE9C2129F6555
        url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/admin_pro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
        username: root

      - dbname: club_pro
        password: DES@402239CE2BC2750281C31F4CEA2619B91D0AE9C2129F6555
        url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/club_pro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
        username: root

logging:
  level:
    root: info
    com.coderman.admin.sync: info
    com.coderman.sync: info