server:
  port: 8989
spring:
  application:
    name: admin
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/admin_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    password: zhangyukang
  redis:
    host: 127.0.0.1
    port: 6379
  task:
    scheduling:
      pool:
        size: 4

sync:
  # 回调&&发送库
  db:
    pub-mq-message: admin_dev
    pub-callback: admin_dev_sync
  # es 配置
  elasticsearch:
    clusterName: docker-cluster
    hosts: 47.115.42.112:9200
    scheme: http
    connectTimeOut: 5000
    socketTimeOut: 60000
    connectionRequestTimeOut: 500
    maxConnectNum: 100
    maxConnectNumPerRoute: 100
    username: elastic
    password:  DES@99D5518076FE8F32214D66F4B59766B7
  # 消息队列配置
  mq: activemq
  rocketmq:
    instantName: SYNC_INSTANT
    namesrvAddr: 47.115.42.112:9876
    retryTimes: 16
    sendMsgTimeoutMillis: 10000
    syncOrderTopic: SYNC_ORDER_TOPIC
    syncTopic: SYNC_TOPIC
    producerGroup: SYNC_PRODUCE_GROUP
    producerOrderGroup: SYNC_PRODUCE_ORDER_GROUP
    consumerGroup: SYNC_CONSUME_GROUP
    consumerOrderGroup: SYNC_CONSUME_ORDER_GROUP
    consumeThreadMax: 10
    consumeThreadMin: 2
  activemq:
    queueName: SYNC_QUEUE_DEV
    brokerUrl: nio://localhost:61616 # vm://localhost
    username: admin
    password: 123456
  # 同步回调配置
  callback:
    destList:
      - project: sync
        url: http://127.0.0.1:8787
  # 同步系统jdbc配置
  jdbc:
    commonMaxIdle: 20
    commonMaxWait: 1000
    commonMinIdle: 10
    commonMaxActive: 800
    commonTimeout: 20
    mysqlUsername: root
    mysqlPassword: 123456
    mysqlInitialSize: 10
    mysqlMinEvictableIdleTimeMillis: 40000
    mysqlTimeBetweenEvictionRunsMillis: 10000
    mysqlTestOnBorrow: false
    mysqlTestOnReturn: false
    mysqlTestWhileIdle: true
    dbList:

      - dbname: admin_dev
        url: jdbc:mysql://127.0.0.1:3306/admin_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: zhangyukang

      - dbname: admin_dev_sync
        url: jdbc:mysql://127.0.0.1:3306/admin_dev_sync?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: zhangyukang

#    - dbname:  ecp_cart_dev
#      url: 127.0.0.1:27017
#      connectionsPerHost: 50
#      connectTimeout: 1000
#      type: mongo
#      maxWaitTime: 1500
#      serverSelectionTimeout: 10000
#      socketKeepAlive: true
#      socketTimeout: 600000
#      threadsAllowedToBlockForConnectionMultiplier: 20
#      password:  DES@99D5518076FE8F32214D66F4B59766B7
#      username: root

# job
job:
  enable: false
  app-name: ${spring.application.name}
  admin-addresses: http://192.168.2.97:8999/xxl-job-admin
  port: 9991
  log-retention-days: 30
  log-path: D:\java\logs\xxl-job

# oss
aliyun:
  oss:
    access-key-id: DES@15BF54A5AE211A5CF9D33FBC5F1DC0BBCBB930C2BCC7C3875F2EC4A83FE5B5FD
    access-key-secret: DES@C198710CB2463E594B6599BE0ABE138AAC0735B5ABBD632655095EBE8F436582
    end-point: oss-cn-shenzhen.aliyuncs.com
    bucket-name: ioss-bucket

# log
logging:
  level:
    root: info
    com.coderman: info
    com.coderman.admin.dao: error
