server:
  port: 8989
spring:
  application:
    name: admin
  datasource:
    username: root
    url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/admin_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    password: DES@402239CE2BC2750281C31F4CEA2619B91D0AE9C2129F6555
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: never
  redis:
    host: 127.0.0.1
    port: 6379
  task:
    scheduling:
      pool:
        size: 4

sync:
  # 回调&&发送库
  db:
    pub-mq-message: admin_dev
    pub-callback: admin_dev_sync
  # es 配置
  elasticsearch:
    clusterName: docker-cluster
    hosts: 47.115.42.112:9200
    scheme: http
    connectTimeOut: 5000
    socketTimeOut: 60000
    connectionRequestTimeOut: 500
    maxConnectNum: 100
    maxConnectNumPerRoute: 100
    username: elastic
    password:  DES@99D5518076FE8F32214D66F4B59766B7
  # 消息队列配置
  mq: activemq
  rocketmq:
    instantName: SYNC_INSTANT
    namesrvAddr: 127.0.0.1:9876
    producerGroup: SYNC_PRODUCE_GROUP
    producerOrderGroup: SYNC_PRODUCE_ORDER_GROUP
    retryTimes: 16
    sendMsgTimeoutMillis: 10000
    syncOrderTopic: SYNC_ORDER_TOPIC
    syncTopic: SYNC_TOPIC
  activemq:
    queueName: SYNC_QUEUE_DEV
    brokerUrl: vm://localhost
    username: admin
    password: 123456
  # 同步回调配置
  callback:
    destList:
      - project: sync
        url: http://127.0.0.1:8787
  # 同步系统jdbc配置
  jdbc:
    commonMaxIdle: 20
    commonMaxWait: 1000
    commonMinIdle: 10
    commonMaxActive: 800
    commonTimeout: 20
    mysqlUsername: root
    mysqlPassword: 123456
    mysqlInitialSize: 10
    mysqlMinEvictableIdleTimeMillis: 40000
    mysqlTimeBetweenEvictionRunsMillis: 10000
    mysqlTestOnBorrow: true
    mysqlTestOnReturn: false
    mysqlTestWhileIdle: true
    dbList:

    - dbname: admin_dev
      url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/admin_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: DES@402239CE2BC2750281C31F4CEA2619B91D0AE9C2129F6555

    - dbname: admin_dev_sync
      url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/admin_dev_sync?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: DES@402239CE2BC2750281C31F4CEA2619B91D0AE9C2129F6555

#    - dbname:  ecp_cart_dev
#      url: 127.0.0.1:27017
#      connectionsPerHost: 50
#      connectTimeout: 1000
#      type: mongo
#      maxWaitTime: 1500
#      serverSelectionTimeout: 10000
#      socketKeepAlive: true
#      socketTimeout: 600000
#      threadsAllowedToBlockForConnectionMultiplier: 20
#      password:  DES@99D5518076FE8F32214D66F4B59766B7
#      username: root

# job
job:
  enable: false
  app-name: ${spring.application.name}
  admin-addresses: http://192.168.2.97:8999/xxl-job-admin
  port: 9991
  log-retention-days: 30
  log-path: D:\java\logs\xxl-job

logging:
  level:
    root: info
    com.coderman.admin: info
    org.elasticsearch: info
    com.alibaba.druid: debug
    com.coderman.sync: info
