package com.coderman.admin.model.user;

import com.coderman.api.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: auth_user_func
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="UserFuncModel", description = "auth_user_func 实体类")
public class UserFuncModel extends BaseModel {
    

    @ApiModelProperty(value = "主键id")
    private Integer userFuncId;

    @ApiModelProperty(value = "用户id")
    private Integer userId;

    @ApiModelProperty(value = "功能id")
    private Integer funcId;
}