package com.coderman.bizedu.model.func;

import com.coderman.api.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Date;

/**
 * This is the base record class for table: auth_func
 * Generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value = "FuncModel", description = "auth_func 实体类")
public class FuncModel extends BaseModel {


    @ApiModelProperty(value = "主键")
    private Integer funcId;

    @ApiModelProperty(value = "功能名称")
    private String funcName;

    @ApiModelProperty(value = "功能key")
    private String funcKey;

    @ApiModelProperty(value = "功能类型(目录/功能)")
    private String funcType;

    @ApiModelProperty(value = "目录图标")
    private String funcIcon;

    @ApiModelProperty(value = "功能排序")
    private Integer funcSort;

    @ApiModelProperty(value = "是否隐藏")
    private String funcDirStatus;

    @ApiModelProperty(value = "父级功能id")
    private Integer parentId;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    private Date updateTime;
}