package com.coderman.bizedu.model.func;

import com.coderman.api.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: auth_func_resc
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="FuncRescModel", description = "auth_func_resc 实体类")
public class FuncRescModel extends BaseModel {
    

    @ApiModelProperty(value = "主键")
    private Integer funcRescId;

    @ApiModelProperty(value = "功能id")
    private Integer funcId;

    @ApiModelProperty(value = "资源id")
    private Integer rescId;
}