server:
  port: 8989
spring:
  application:
    name: bizedu
  datasource:
    username: root
    password: DES@99D5518076FE8F32214D66F4B59766B7
    url: jdbc:mysql://127.0.0.1:3306/bizedu_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: wx.yswg.com.cn
    password: yswg@2019
    port: 6379
aliyun:
  oss:
    access-key-id: DES@15BF54A5AE211A5CF9D33FBC5F1DC0BBCBB930C2BCC7C3875F2EC4A83FE5B5FD
    access-key-secret: DES@C198710CB2463E594B6599BE0ABE138AAC0735B5ABBD632655095EBE8F436582
    end-point: oss-cn-shenzhen.aliyuncs.com
    bucket-name: ioss-bucket


#服务端配置
sync:
  store:
    type: activemq
  # es 配置
  elasticsearch:
    clusterName: sync
    hosts: 127.0.0.1:9200
    # hosts: 165.154.133.250:9200
    scheme: http
    connectTimeOut: 5000
    socketTimeOut: 60000
    connectionRequestTimeOut: 500
    maxConnectNum: 100
    maxConnectNumPerRoute: 100
  # rocketMQ配置
  rocketmq:
    namesrvAddr: 127.0.0.1:9876
    instancename: SYNC_SERVER
    consumerGroup: SYNC_CONSUMER
    consumerOrderGroup: SYNC_ORDER_CONSUMER
    topic: SYNC_TOPIC_DEV
    orderTopic: SYNC_ORDER_TOPIC_DEV
    consumeThreadMin: 20
    consumeThreadMax: 40
  # activeMQ配置
  activemq:
    queueName: SYNC_QUEUE_DEV
    brokerUrl: nio://127.0.0.1:61616
  # 同步回调配置
  callback:
    destList:
      - project: demo
        url: http://127.0.0.1:8084
  # 同步系统jdbc配置
  jdbc:
    commonMaxIdle: 20
    commonMaxWait: 1000
    commonMinIdle: 10
    commonMaxActive: 800
    commonTimeout: 20
    mysqlUsername: root
    mysqlPassword: 123456
    mysqlInitialSize: 10
    mysqlMinEvictableIdleTimeMillis: 40000
    mysqlTimeBetweenEvictionRunsMillis: 10000
    mysqlTestOnBorrow: false
    mysqlTestOnReturn: false
    mysqlTestWhileIdle: true
    dbList:

    - dbname: base_auth
      url: jdbc:mysql://localhost:3306/base_auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: DES@99D5518076FE8F32214D66F4B59766B7
      message: true

    - dbname:  ecp_cart_dev
      url: 127.0.0.1:27017
      connectionsPerHost: 50
      connectTimeout: 1000
      type: mongo
      maxWaitTime: 1500
      serverSelectionTimeout: 10000
      socketKeepAlive: true
      socketTimeout: 600000
      threadsAllowedToBlockForConnectionMultiplier: 20
      password:  DES@99D5518076FE8F32214D66F4B59766B7
      username: root

logging:
  level:
    root: info
    com.coderman.bizedu.sync: info
    com.coderman.sync: info