server:
  port: 8989
spring:
  application:
    name: bizedu
  datasource:
    username: root
    password: DES@99D5518076FE8F32214D66F4B59766B7
    url: jdbc:mysql://127.0.0.1:3306/bizedu_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: wx.yswg.com.cn
    password: yswg@2019
    port: 6379
aliyun:
  oss:
    access-key-id: DES@15BF54A5AE211A5CF9D33FBC5F1DC0BBCBB930C2BCC7C3875F2EC4A83FE5B5FD
    access-key-secret: DES@C198710CB2463E594B6599BE0ABE138AAC0735B5ABBD632655095EBE8F436582
    end-point: oss-cn-shenzhen.aliyuncs.com
    bucket-name: ioss-bucket

# 同步系统客户端
sync:
  rocketmq:
    syncTopic: SYNC_TOPIC_DEV
    syncOrderTopic: SYNC_ORDER_TOPIC_DEV
    producerGroup: BASE_AUTH_GROUP_DEV
    producerOrderGroup: BASE_AUTH_ORDER_GROUP_DEV
    namesrvAddr: 127.0.0.1:9876
    sendMsgTimeoutMillis: 5000
    retryTimes: 16
    instantName: BASE_AUTH_INSTANT_DEV
  activemq:
    brokerUrl: tcp://localhost:61616
    queueName: SYNC_QUEUE_DEV
logging:
  level:
     root: info
     com.coderman.sync: info