server:
  port: 8989
spring:
  application:
    name: bizedu
  datasource:
    username: root
    password: DES@2120FA78BC6EB99B019C119BD8067DB0
    url: jdbc:mysql://localhost:3306/bizedu_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true