server:
  port: 8989
spring:
  application:
    name: bizedu
  datasource:
    username: root
    password: DES@99D5518076FE8F32214D66F4B59766B7
    url: jdbc:mysql://127.0.0.1:3306/bizedu_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true