server:
  port: 8989
spring:
  application:
    name: bizedu
  datasource:
    username: root
    password: DES@D701B4AAF2392EEA7A1AE73801A12C7DCB0D9A55012E8988
    url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/bizedu_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: wx.yswg.com.cn
    password: DES@D59EF7CAF79ADAD55BFE9AE4772B78A7
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true