package com.coderman.bizedu.edu.model.chapter;

import com.coderman.api.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: edu_chapter
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="ChapterModel", description = "edu_chapter 实体类")
public class ChapterModel extends BaseModel {
    

    @ApiModelProperty(value = "课程章节id")
    private Integer chapterId;

    @ApiModelProperty(value = "章节标题")
    private String chapterName;

    @ApiModelProperty(value = "课程id")
    private Integer courseId;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    private Date updateTime;
}