package com.coderman.bizedu.edu.model.catalog;

import com.coderman.api.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: edu_catalog
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="CatalogModel", description = "edu_catalog 实体类")
public class CatalogModel extends BaseModel {
    

    @ApiModelProperty(value = "分类id")
    private Integer catalogId;

    @ApiModelProperty(value = "分类名称")
    private String catalogName;

    @ApiModelProperty(value = "父级分类")
    private Integer parentId;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    private Date updateTime;
}