package com.coderman.admin.model.common;

import com.coderman.api.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: auth_notification
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="NotificationModel", description = "auth_notification 实体类")
public class NotificationModel extends BaseModel {
    

    @ApiModelProperty(value = "主键")
    private Integer notificationId;

    @ApiModelProperty(value = "消息通知类型")
    private String notificationType;

    @ApiModelProperty(value = "被通知人id")
    private Integer userId;

    @ApiModelProperty(value = "消息已读时间")
    private Date readTime;

    @ApiModelProperty(value = "是否已读 0-未读,1-已读")
    private Integer isRead;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    private Date updateTime;

    @ApiModelProperty(value = "消息通知数据(json)")
    private String data;
}